#include "plugins.h"

POCO_BEGIN_MANIFEST(Base)
    POCO_EXPORT_CLASS(Dog)
    POCO_EXPORT_CLASS(Cat)
    POCO_EXPORT_CLASS(Duck)
    POCO_EXPORT_CLASS(Cow)
    POCO_EXPORT_CLASS(Sheep)
POCO_END_MANIFEST

