#include "plugins.h"

PLUGIN_LOADER_REGISTER_CLASS(Dog, Base)
PLUGIN_LOADER_REGISTER_CLASS(Cat, Base)
PLUGIN_LOADER_REGISTER_CLASS(Duck, Base)
PLUGIN_LOADER_REGISTER_CLASS(Cow, Base)
PLUGIN_LOADER_REGISTER_CLASS(Sheep, Base)
